### ISSUE TITLE
One pen to draw them all advancement given automatically

### ISSUE THREAD

**Issue by NillerMedDild** [stfwi/redstonepen#10]
The `One pen to draw them all` advancement is given to the player as soon as anything enters their inventory the first time.

**Comment by stfwi** [comment]
Hi NillerMed, oky let me have a look at this (the first advancement I ever made, yay) - it worked fine on my SMP server strangely. 
Was this in on a new world (e.g. your setup) or could people have already had the pen in the inventory before, so that the advancement triggered because it was added later? Cheers,-

**Comment by stfwi** [comment]
Okay, MC1.16 somehow has a problem with that advancement JSON, I presume the advancement is anyway important to a "major minority", so I simply removed it for the back port. The fix version is `redstonepen-1.16.5-1.0.8-b3`.  It's already in the approval process on Curse. 
Thanks again for the hint! Cheers,-

**Comment by NillerMedDild** [comment]
Thank you kindly :D
