### ISSUE TITLE
Can RLC be strengthened?

### ISSUE THREAD

**Issue by litobutter** [stfwi/redstonepen#17]
When I was writing the RLC program and found that there was not enough space,Can you add more writing space?,In addition, can all RLC share all variables?This will give RLC more possibilities

**Comment by litobutter** [comment]
1.18.2

**Comment by stfwi** [comment]
Hi, ty for reaching out. The one-page program is actually a design decision. There are several thoughts behind this.
The RLC calculates all lines in one game tick. Although the program is pre-parsed and the calculation is fast, I don't like to risk that the block may have performance impacts on smaller servers or weaker PCs.
The Pen mod has to fit into a vanilla context. So the recipes and ingredients should be simple and without multi-step micro-crafting. It should be usable to simplify/compact smaller Redstone tasks - but should have limitations, too. Limiting the "program ROM memory" is one of the ways doing this.
I also left out stuff like wireless connections, data bus, track colors, etc. That's all not in the mod by design - Standard Redstone only ;).

**Comment by litobutter** [comment]
Does that allow RLC to share custom variables?

**Comment by litobutter** [comment]
So can RLC share custom variables?

**Comment by stfwi** [comment]
Hi, sorry about the delayed response. No, the intended interface between RLCs is using redstone signals. Only exception are the I/Os of the Redstone Client Adapter (https://github.com/stfwi/redstonepen/tree/redstone-client-adapter), but this is intended for people who like to connect hardware (micro controllers, etc) to Minecraft via the RLCs. RCA is disabled by default, because very few players use it.
As said, there are many redstone mods around, of which quite a few (CC, McJtys tools, etc) provide complex data busses. I don't like to copy that, but provide a mod complementing these. So the RLC should not be too powerful. Cheers,-

**Comment by stfwi** [comment]
Oky, a few lines were added by tacking the font size (also increases the line length). Looks reasonably spaced now for this block. Cheers,-
