### ISSUE TITLE
Redstone Tracks cannot stick to blocks using the super glue of Create mod

### ISSUE THREAD

**Issue by XiaoLey** [stfwi/redstonepen#23]
The super glue of the Create mod cannot affect the redstone track, which means that the redstone track cannot be attached to the structure formed by create like the original redstone, but other items provided by the redstone pen mod, such as the redstone relay, can be attached well.

**Comment by stfwi** [comment]
Hi, thanks for reaching out. I'm aware of that problem, unfortunately I don't have a proper technical solution for it.
The reason why this is problematic is that the Redstone Tracks of the mod require Block Entities to work - otherwise the mod would use an enormous amount of RAM for models (generated when the game is starting), and would also suffer performance, which is especially on smaller servers an unwanted side effect.
The relays are only blocks (without Block Entities), Create can easily handle those without a problem.

In future Minecraft versions there may be a proper way to handle these situations, for the moment I'll have to defer handling that issue. Cheers,-

**Comment by XiaoLey** [comment]
Oh, I see, thanks for your reply.

**Comment by XiaoLey** [comment]
After the Create mod was updated to version 0.5.0g, this issue was resolved.

**Comment by stfwi** [comment]
Wow, so they must have found a stable way to "simulate" a static context for block entities in Create contraption? That is pretty cool. Thanks for the info xiaoley, Cheers,-
