### ISSUE TITLE
Resource Pack compatibility?

### ISSUE THREAD

**Issue by Jack-Chronicle** [stfwi/redstonepen#43]
Would be great if the redstone track placed with the quill/pen could copy the look and appearance of the Redstone Dust that is being used by the current Resource Pack

I tend to use the Vanilla Tweaks solid redstone dust pack, and would really love if there was a way to have the appearance of that used for the track placed as well

**Comment by stfwi** [comment]
Hi Jack, ty for the feedback. From initial checks (I asked around) it turned out that people had the tendency to prefer distinguishable Pen Tracks from vanilla Redstone wires, so I made the Tracks slightly thinner to project that.

It's still possible to override these designs (except the redstone colors for different powers) in a texture pack. An example is the [Create Style Redstone Pen](https://www.curseforge.com/minecraft/texture-packs/redstone-pen-revamped), which looks really great.

As a mod dev I focus more on features and the functionality ;)

Cheer's,-

**Comment by stfwi** [comment]
Closing, resolution is by using a texture pack. Cheers,-
