### ISSUE TITLE
The .FO suffix works like .FE, but is not listed in documentation

### ISSUE THREAD

**Issue by Aerotactics** [stfwi/redstonepen#46]
I realized just a bit ago I had a typo in my code, where I wanted the Falling Edge of a pulse. I typed .FO, and the code still ran as expected.

![image](https://github.com/user-attachments/assets/45ba9abc-46fc-477a-a6f6-4051189976cd)

**Comment by stfwi** [comment]
Hi, which version/modloader are you using, for better bug searching ;)

The behaviour I expect here is:
- `V` is 15 for comparator override 0 or 1 on `R`ed.
- Redstone output of `R`ed is the comparator override on Red >= 2 (the `.FO` should be ignored).
- `D`own is 15 when comparator override 0 or 1 on `R`ed (`V`>0) , and one tick after that.

IIRC I do not mark a parse error if the suffixes are not explicitly `.fe`, `.re`, `.co`, I think that's the problem here.

The java code handling the edge detection symbols in the RLC code is here. So, edge detection should work for ".FE" and ".RE":

https://github.com/stfwi/redstonepen/blob/d2acc717ce75b24f038018992025e29ecfdab59c/src/main/java/wile/redstonepen/blocks/ControlBox.java#L1088-L1111

**Comment by Aerotactics** [comment]
Sorry for not including it originally. I agree adding a syntax error would help with the confusion.

Mod version: 1.11.34 Fabric

I believe you are correct, the .FO should be ignored, however try this code in an empty RPC:

D = !R.FO

I put a redstone lamp under it. IF the .FO is ignored completely, then adding power to R should turn it off and on (as it does with D = !R), but D stays on instead. (This might be a different bug)

**Comment by Aerotactics** [comment]
OK yeah, I misunderstood the bug. "D = R.FO" is acting like "D = 15". I expect that if a suffix is ignored, the code should still process normally.

**Comment by stfwi** [comment]
It should see R.FO as an own symbol that holds 0 all the time. Fixing approach will be likely in the parser; Cheers,-

**Comment by stfwi** [comment]
Oky, will be fixed in v1.11.35, added parse error indication for unknown symbol suffixes:

![image](https://github.com/user-attachments/assets/4544c70f-fb67-48c6-92cb-c7fbe052c7e6)

**Comment by stfwi** [comment]
Oky, version v1.21-1.11.35 is up on curse and modrinth. Let's close this one. Cheer's,-
