### ISSUE TITLE
Incompatibility with Wilder Wilds

### ISSUE THREAD

**Issue by Aerotactics** [stfwi/redstonepen#47]
Running the mod with Wilder Wild causes a crash on launch

Mod in question: https://modrinth.com/mod/wilder-wild

Crash Report: https://paste.debian.net/plainh/cad4182d

**Comment by stfwi** [comment]
Ty for registering it on the hub. Initial checks indicate it's a Heisen-Bug, `getResourceManager()` returns null is what I get. Either it gets reloaded in the WW frozen lib somehow, or the Pen mod provokes it itself somehow. After updating Loom I don't get the crash anymore - which is worse, because the problem is assumingly not solved by that.

**Comment by stfwi** [comment]
The fix attempt is pushed to curse and modrinth, `v1.21-1.11.35`, here we need confirmation if that really resolved the issue on the target machine.
